# Generated by Django 5.2.1 on 2025-05-31 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WasteType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WasteBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('opening_hours_senin', models.TimeField()),
                ('opening_hours_selasa', models.TimeField()),
                ('opening_hours_rabu', models.TimeField()),
                ('opening_hours_kamis', models.TimeField()),
                ('opening_hours_jumat', models.TimeField()),
                ('opening_hours_sabtu', models.TimeField()),
                ('opening_hours_minggu', models.TimeField()),
                ('waste_processed', models.ManyToManyField(to='eco_vision_api_bank_app.wastetype')),
            ],
        ),
    ]
