# Generated by Django 5.2.1 on 2025-05-31 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco_vision_api_bank_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wastebank',
            name='opening_hours_jumat',
        ),
        migrations.RemoveField(
            model_name='wastebank',
            name='opening_hours_kamis',
        ),
        migrations.RemoveField(
            model_name='wastebank',
            name='opening_hours_minggu',
        ),
        migrations.RemoveField(
            model_name='wastebank',
            name='opening_hours_rabu',
        ),
        migrations.RemoveField(
            model_name='wastebank',
            name='opening_hours_sabtu',
        ),
        migrations.RemoveField(
            model_name='wastebank',
            name='opening_hours_selasa',
        ),
        migrations.RemoveField(
            model_name='wastebank',
            name='opening_hours_senin',
        ),
        migrations.CreateModel(
            name='OpeningHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('senin', 'Senin'), ('selasa', 'Selasa'), ('rabu', 'Rabu'), ('kamis', 'Kamis'), ('jumat', 'Jumat'), ('sabtu', 'Sabtu'), ('minggu', 'Minggu')], max_length=10)),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_hours', to='eco_vision_api_bank_app.wastebank')),
            ],
            options={
                'unique_together': {('bank', 'day')},
            },
        ),
    ]
