# Generated by Django 5.2.1 on 2025-05-31 08:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco_vision_api_bank_app', '0002_remove_wastebank_opening_hours_jumat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openinghour',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wastebank',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wastetype',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
